MODULE PARAMS 
	IMPLICIT NONE
	INTEGER, PARAMETER       :: MAX_ITERATION = 30
	INTEGER, PARAMETER 	     :: NUM_GRID = 100
	REAL, PARAMETER          :: TOLERANCE = 1.0E-6
	REAL, PARAMETER          :: PI = 3.141592653589793
END MODULE PARAMS 
